Lesson 1: Javascript, Add/Test
seemcat/garage_script pull request #1
Opened 2017-08-15 22:12 UTC by seemcat

2017-08-15 22:33 UTC, allopez7 approved these changes
Good Job!!!

2017-08-15 22:35 UTC, saumya665 approved these changes

2017-08-15 22:35 UTC, saumya665 commented on testSum.js
> +  if(add(a,b) === c){
can use double equals sign

2017-08-15 22:48 UTC, allopez7 requested changes
Can you change a,b,c into more descriptive names?

2017-08-15 22:48 UTC, allopez7 commented on testSum.js
> +const testSum = (a, b, c) => {
Can you change a,b,c into more descriptive names?

2017-08-15 22:54 UTC, seemcat commented on testSum.js
> +const testSum = (a, b, c) => {
Yes!

2017-08-15 22:57 UTC, allopez7 commented on sum.js
> +  return a + b;
Change a,b here as well to more descriptive names.

2017-08-16 02:21 UTC, seemcat commented on sum.js
> +  return a + b;
Done!

2017-08-16 02:23 UTC, dsope05 commented
APPROVED

2017-08-16 02:25 UTC, dsope05 approved these changes

2017-08-16 02:30 UTC, allopez7 approved these changes

2017-08-16 02:38 UTC, merged